### ISSUE TITLE
Reimplement Tests

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#25]
While moving over work done on the Azure Explorer, testing was lost - mostly because it assumes that it runs in NW.js. We need to reimplement testing and get cracking on some good integration and unit tests. It's fine if tests are failing - I actually assume that good tests would find a bunch of edge cases we're currently not handling well.

- [x] Reimplement JavaScript Code Style Testing
- [x] Reimplement Phantom.js Testing
- [x] Mock Login API and write tests (#22)
- [x] Mock Device API and write tests (#24)

**Comment by sedouard** [comment]
Done!
